/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade07.view;

/**
 *
 * @author Casa
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValor = new javax.swing.JLabel();
        btncalcularFatorial = new javax.swing.JButton();
        spnFatoriado = new javax.swing.JSpinner();
        lblFormula = new javax.swing.JLabel();
        lblcontroledeErros = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValor.setText("Valor :");

        btncalcularFatorial.setText("Calcular");
        btncalcularFatorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcularFatorialActionPerformed(evt);
            }
        });

        spnFatoriado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblFormula)
                    .addComponent(lblValor))
                .addGap(18, 18, 18)
                .addComponent(spnFatoriado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblcontroledeErros)
                    .addComponent(btncalcularFatorial))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblcontroledeErros)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValor)
                    .addComponent(btncalcularFatorial)
                    .addComponent(spnFatoriado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(lblFormula)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btncalcularFatorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcularFatorialActionPerformed
        // TODO add your handling code here:
       
   int valor = (int)spnFatoriado.getValue(); // puxar valor do spinner
   
   
   if(valor < 0){
   
   lblcontroledeErros.setText("NÃO HÁ FATORIAL DE NÚMERO NEGATIVO");
   return;//encerrrar a funçao
   
   }
   
    if(valor > 10){
   
   lblcontroledeErros.setText("NÚMERO MUITO GRANDE");
   return;//encerrrar a funçao
   
   }
    
    Fatorial fatorial = new Fatorial(); // declarado como objeto
    
    fatorial.setValor(valor); //puxar esse valor do spinner e jogar no método
    
    if(valor == 1){
        lblFormula.setText("1! = 1");
        lblcontroledeErros.setText(""); // Limpa mensagens de erro quando o valor é válido
    }    
    
    else if(valor == 0){
       
        lblFormula.setText("0! = 1");
    
    }  else if ( valor > 1){
        
    lblcontroledeErros.setText(""); // Limpa mensagens de erro quando o valor é válido
    
    lblFormula.setText(fatorial.getFormula()); // chamo a funçao direto da classe
    
            }
    }//GEN-LAST:event_btncalcularFatorialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcularFatorial;
    private javax.swing.JLabel lblFormula;
    private javax.swing.JLabel lblValor;
    private javax.swing.JLabel lblcontroledeErros;
    private javax.swing.JSpinner spnFatoriado;
    // End of variables declaration//GEN-END:variables
}
