/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.view;
import java.util.Random;//poder usar o random
/**
 *
 * @author Casa
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        
       lblfaladoGenio.setText("<html>Estou pensando em um número entre<br> 1 e 5 tente advinhar qual é!</html>");//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlGenio = new javax.swing.JPanel();
        lblfaladoGenio = new javax.swing.JLabel();
        lblbalaodeFala = new javax.swing.JLabel();
        lblGenio = new javax.swing.JLabel();
        spnNum = new javax.swing.JSpinner();
        btnPalpite = new javax.swing.JButton();
        lblvalorPalpite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlGenio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblfaladoGenio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        pnlGenio.add(lblfaladoGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));

        lblbalaodeFala.setIcon(new javax.swing.ImageIcon("C:\\Users\\Casa\\Downloads\\balãop_de_fala-removebg-preview.png")); // NOI18N
        pnlGenio.add(lblbalaodeFala, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, -1, -1));

        lblGenio.setIcon(new javax.swing.ImageIcon("C:\\Users\\Casa\\Downloads\\akinator-removebg-preview.png")); // NOI18N
        pnlGenio.add(lblGenio, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 320, 300));
        pnlGenio.add(spnNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 80, 30));

        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalpiteActionPerformed(evt);
            }
        });
        pnlGenio.add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        lblvalorPalpite.setText("Valor:");
        pnlGenio.add(lblvalorPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 40, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGenio, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlGenio, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
 
    
    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalpiteActionPerformed
       
        Random random = new Random();  // criar objeto random
        
        int numdogenio = 1 + random.nextInt(5);// entre um e cinco
        
        int palpite = (int)spnNum.getValue(); // pegar o valor do spinner
        
        if(palpite < 1 || palpite > 5 ){
        
            lblfaladoGenio.setText("<html>Nana nina não<br>isso não ta no intervalo</html>");
            
            new javax.swing.Timer(2500, e -> {//definie  açao em miliseg
                lblfaladoGenio.setText("");//reseta o campo de texto
            ((javax.swing.Timer)e.getSource()).stop();//chama o timer e  encerra-o
        }).start();//iniciar o timer
            
            lblfaladoGenio.setText("Tente de novo!!");
            
            } else {
            
}
        if(palpite == numdogenio){
            
        lblfaladoGenio.setText("Acertou!!");
        
        } else{
        
         lblfaladoGenio.setText("Na verdade eu pensei no " +numdogenio);
            
        }
        
        
    }//GEN-LAST:event_btnPalpiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel lblGenio;
    private javax.swing.JLabel lblbalaodeFala;
    private javax.swing.JLabel lblfaladoGenio;
    private javax.swing.JLabel lblvalorPalpite;
    private javax.swing.JPanel pnlGenio;
    private javax.swing.JSpinner spnNum;
    // End of variables declaration//GEN-END:variables
}
